In [2]:
import unittest
import pandas as pd
import numpy as np
import torch
import torchvision


In [3]:
# Ejemplos de operaciones básicas con el tensor

# Ejercicio 1: Crear un tensor de 2x3 lleno de ceros
tensor_zeros = torch.zeros((2, 3))
print("Tensor de ceros:\n", tensor_zeros)

Tensor de ceros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [4]:
# Ejercicio 2: Crear un tensor de 3x3 lleno de unos
tensor_ones = torch.ones((3, 3))
print("Tensor de unos:\n", tensor_ones)

Tensor de unos:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [5]:
# Ejercicio 3: Crear un tensor aleatorio de 3x3
tensor_random = torch.rand((3, 3))
print("Tensor aleatorio:\n", tensor_random)


Tensor aleatorio:
 tensor([[0.0429, 0.9303, 0.3363],
        [0.5055, 0.3684, 0.4866],
        [0.6468, 0.6559, 0.2373]])


In [7]:
# Ejercicio 5: Operaciones con tensores
tensor_a = torch.tensor([1, 2, 3])
tensor_b = torch.tensor([4, 5, 6])
tensor_sum = tensor_a + tensor_b
print("Suma de tensores:\n", tensor_sum)

tensor_product = tensor_a * tensor_b
print("Producto de tensores:\n", tensor_product)


Suma de tensores:
 tensor([5, 7, 9])
Producto de tensores:
 tensor([ 4, 10, 18])


In [8]:
# Ejercicio 6: Más operaciones con tensores
tensor_mean = torch.mean(tensor_random)
print("Media de tensor aleatorio:\n", tensor_mean)

Media de tensor aleatorio:
 tensor(0.4678)


In [9]:
tensor_std = torch.std(tensor_random)
print("Desviación estándar de tensor aleatorio:\n", tensor_std)

Desviación estándar de tensor aleatorio:
 tensor(0.2608)


In [11]:
# Ejercicio 7: Reestructuración de un tensor
tensor_reshape = tensor_zeros.view(3, 2)
print("Tensor de ceros reestructurado:\n", tensor_reshape)

Tensor de ceros reestructurado:
 tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
